[tools]
# language runtime
"java" = { version = "corretto-17.0.14.7", release_type = "ga" }
"rust" = "1.91.0"
"go" = "1.25.4"
"node" = "24.11.0"
"lua" = "5.4.8"
"npm:vite" = "7.2.2"
"npm:vitest" = "4.0.8"
"npm:zenn-cli" = "0.2.10"
"npm:@anthropic-ai/claude-code" = "2.0.35"
"npm:@marp-team/marp-cli" = "latest"
"npm:sv" = '0.9.13'
"npm:tsx" = '4.20.6'
"npm:playwright" = '1.56.1'
'npm:@modelcontextprotocol/inspector' ='0.17.2'
"cargo:leetcode-cli" = "latest"
"spring-boot" = "3.5.3"
[settings]
experimental = false
