[tools]
# language runtime
"java" = { version = "corretto-17.0.14.7", release_type = "ga" }
"rust" = "1.91.1"
"go" = "1.25.4"
"node" = "24.11.1"
"lua" = "5.4.8"
"npm:vite" = "7.2.4"
"npm:vitest" = "4.0.14"
"npm:zenn-cli" = "0.2.10"
"npm:@anthropic-ai/claude-code" = "2.0.55"
"npm:@marp-team/marp-cli" = "latest"
"npm:sv" = '0.9.13'
"npm:tsx" = '4.20.6'
"npm:playwright" = '1.56.1'
'npm:@modelcontextprotocol/inspector' ='0.17.2'
#"cargo:leetcode-cli" = "latest"
"spring-boot" = "3.5.3"
"npm:@openapitools/openapi-generator-cli" = 'latest'
[settings]
experimental = false
