[tools]
    # language runtime
    "java" = { version = "corretto-17.0.14.7", release_type = "ga" }
    "rust" = "1.93.0"
    "go" = "1.25.7"
    "node" = "24.13.1"
    "lua" = "5.5.0"
    "dotnet" = "10.0.102"
    "npm:vite" = "7.3.1"
    "npm:vitest" = "4.0.18"
    "npm:zenn-cli" = "0.4.5"
    "npm:@marp-team/marp-cli" = "latest"
    "npm:sv" = '0.12.0'
    "npm:tsx" = '4.21.0'
    "npm:playwright" = '1.58.2'
    'npm:@modelcontextprotocol/inspector' = '0.19.0'
    #"cargo:leetcode-cli" = "latest"
    "spring-boot" = "3.5.3"
    "npm:@openapitools/openapi-generator-cli" = 'latest'
    "wrangler" = "4.61.1"
[settings]
    experimental = false
