[tools]
# language runtime
"java" = { version = "corretto-17.0.14.7", release_type = "ga" }
"rust" = "1.92.0"
"go" = "1.25.5"
"node" = "24.12.0"
"lua" = "5.4.8"
"npm:vite" = "7.3.0"
"npm:vitest" = "4.0.16"
"npm:zenn-cli" = "0.2.11"
"npm:@anthropic-ai/claude-code" = "2.0.73"
"npm:@marp-team/marp-cli" = "latest"
"npm:sv" = '0.10.8'
"npm:tsx" = '4.21.0'
"npm:playwright" = '1.57.0'
'npm:@modelcontextprotocol/inspector' ='0.17.5'
#"cargo:leetcode-cli" = "latest"
"spring-boot" = "3.5.3"
"npm:@openapitools/openapi-generator-cli" = 'latest'
[settings]
experimental = false
