---
name: Renovate Auto-merge

on:
  pull_request:
    types: [opened, synchronize, labeled]

permissions:
  contents: write
  pull-requests: write

jobs:
  renovate-automerge:
    runs-on: ubuntu-24.04-arm
    if: ${{ github.actor == 'renovate[bot]' }}
    steps:
      - name: Auto-merge Renovate PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
